name: CI CD Pipeline for Infra deployments
run-name: ${{ github.actor }} has triggered thepipeline

on:
  push:
    branches: 
    - 'main'

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

jobs:
  build_infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ./vpc
      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ./vpc
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./vpc
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./vpc           